name: Amnesia
on: 
  workflow_dispatch:

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4.2.2

    - name: Set up secret file
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID}}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET}}
        NEW_MUSIC_FRIDAY_DANCE_ID: ${{ secrets.NEW_MUSIC_FRIDAY_DANCE_ID}}
        NEW_MUSIC_FRIDAY_ID: ${{ secrets.NEW_MUSIC_FRIDAY_ID}}
        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN}}
        SAVE_TO_ID: ${{ secrets.SAVE_TO_ID}}
        USER_ID: ${{ secrets.USER_ID}}
      run: |
        echo $CLIENT_ID >> secrets.txt
        echo $CLIENT_SECRET >> secrets.txt
        echo $NEW_MUSIC_FRIDAY_DANCE_ID >> secrets.txt
        echo $NEW_MUSIC_FRIDAY_ID >> secrets.txt
        echo $REFRESH_TOKEN >> secrets.txt
        echo $SAVE_TO_ID >> secrets.txt
        echo $USER_ID >> secrets.txt
    - name: Run tmate
      uses: mxschmitt/action-tmate@v3.19
